- name: Stopped kesl
  ansible.builtin.service:
    name: "kesl"
    state: stopped

- name: Stopped klnagent
  ansible.builtin.service:
    name: "klnagent64"
    state: stopped

- name: Stopped kesl
  ansible.builtin.service:
    name: "kesl"
    enabled: false

- name: Stopped klnagent
  ansible.builtin.service:
    name: "klnagent64"
    enabled: false

- name: Debian delete pkgs
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Astra Linux'
  block:
    - name: "Remove previous klnagent installations"
      ansible.builtin.apt:
        name: klnagent64
        state: absent

    - name: "Remove previous kesl installations"
      ansible.builtin.apt:
        name: kesl
        state: absent

- name: RHEL delete pkgs
  when: ansible_facts['os_family'] == 'RED' or ansible_facts['os_family'] == 'RedHat'
  block:
    - name: "Remove previous agent installations"
      ansible.builtin.yum:
        name: klnagent64
        state: absent

    - name: "Remove previous kesl installations"
      ansible.builtin.yum:
        name: kesl
        state: absent

- name: Clear /opt/kaspersky
  ansible.builtin.file:
    path: "/opt/kaspersky"
    state: absent

- name: Clear /var/opt/kasperksy
  ansible.builtin.file:
    path: "/var/opt/kaspersky"
    state: absent
