- name: Debian delete pkgs
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: "Remove previous klnagent installations"
      ansible.builtin.apt:
        name: klnagent64
        state: absent

    - name: "Remove previous kesl installations"
      ansible.builtin.apt:
        name: kesl
        state: absent

- name: RHEL delete pkgs
  when: ansible_facts['os_family'] == 'RED' or ansible_facts['os_family'] == 'RedHat'
  block:
    - name: "Remove previous agent installations"
      ansible.builtin.yum:
        name: klnagent64
        state: absent

    - name: "Remove previous kesl installations"
      ansible.builtin.yum:
        name: kesl
        state: absent

- name: Clear /opt/kaspersky/klnagent64
  ansible.builtin.file:
    path: "/opt/kaspersky/klnagent64"
    state: absent
- name: Clear /var/opt/kasperksy/klnagent64
  ansible.builtin.file:
    path: "/var/opt/kasperksy/klnagent64"
    state: absent

- name: "Deleting previous configs from /opt/kaspersky/kesl"
  ansible.builtin.file:
    path: "/opt/kaspersky/kesl"
    state: absent
- name: "Deleting previous configs from /var/opt/kaspersky/kesl"
  ansible.builtin.file:
    path: "/var/opt/kaspersky/kesl"
    state: absent
