all:
  vars:
    ansible_user: marker

  children:
    debian:
      hosts:
        debian_host1:
          ansible_host: 192.168.103.100
#        debian_host2:
#          ansible_host: 192.168.1.102
      vars:
        ansible_become_method: sudo 
    rhel:
      hosts:
        rhel_host1:
          ansible_host: 192.168.103.101
#        rhel_host2:
#          ansible_host: 192.168.1.103
      vars:
        ansible_become_method: su 