- name: Install KESL to RedHat like OS
  when: ansible_facts['os_family'] == 'RED' or ansible_facts['os_family'] == 'RedHat'
  block:
    - name: "Getting kesl install package to temporary folder"
      ansible.builtin.copy:
        src: "{{ kesl_distrib_local_folder }}/{{ kesl_rpm_package_name }}"
        dest: "{{ kesl_distrib_remote_folder }}"
        mode: "0755"

    - name: Installing perl-File-Copy package
      ansible.builtin.yum:
        name: perl-File-Copy

    - name: Installing kesl package
      ansible.builtin.yum:
        name: "{{ kesl_distrib_remote_folder }}/{{ kesl_rpm_package_name }}"
        disable_gpg_check: true

- name: Install KESL to Debian like OS
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Astra Linux'
  block:
    - name: Getting kesl install package to temporary folder
      ansible.builtin.copy:
        src: "{{ kesl_distrib_local_folder }}/{{ kesl_deb_package_name }}"
        dest: "{{ kesl_distrib_remote_folder }}"
        mode: "0755"
    - name: "Installing kesl package"
      ansible.builtin.apt:
        deb: "{{ kesl_distrib_remote_folder }}/{{ kesl_deb_package_name }}"

- name: Creating answer file for kesl
  ansible.builtin.template:
    src: kesl.j2
    dest: "{{ kesl_answer_file_path }}"
    mode: "0644"

- name: Run configuring kesl
  ansible.builtin.command: "/opt/kaspersky/kesl/bin/kesl-setup.pl --autoinstall={{ kesl_answer_file_path }}"
  changed_when: false
  notify: Restart kesl

- name: Ensure kesl service is enabled and restarted
  ansible.builtin.service:
    name: kesl
    enabled: true
    state: restarted
