- name:  Install KESL to RedHat like OS
  block:
    - name: "Getting kesl install package to temporary folder"
      copy:
        src: "/tmp/kesl_red.rpm"
        dest: "/tmp"
        mode: 0755
    - name: "Installing kesl package"
      dnf:
        name: /tmp/kesl_red.rpm
    - name: "Deleting distros"
      file:
        path: "/tmp/klnagent_red.rpm"
        state: absent
  when: ansible_facts['os_family'] == 'RED' or ansible_facts['os_family'] == 'RedHat'

- name:  Install KESL to Debian like OS
  block:
    - name: "Getting kesl install package to temporary folder"
      copy:
        src: "/tmp/kesl_deb.deb"
        dest: "/tmp"
        mode: 0755
    - name: "Installing kesl package"
      apt:
        deb: /tmp/kesl_deb.deb
    - name: "Deleting distros"
      file:
        path: "/tmp/kesl_deb.deb"
        state: absent
  when: ansible_facts['os_family'] == 'Debian'


- block:
    - name: "Creating answer file for kesl"
      become: true
      template:
        src: kesl.j2
        dest: /tmp/kesl.ini
        mode: 0644

    - name: "Run configuring kesl"
      become: true
      shell: "/opt/kaspersky/kesl/bin/kesl-setup.pl --autoinstall=/tmp/kesl.ini"
      args:
        executable: /bin/bash
      notify: restart kesl

    - name: "Ensure kesl service is enabled"
      become: true
      service:
        name: kesl
        enabled: yes
        state: started
