---
- name: Installing RPM to RedHat Like
  when: ansible_facts['os_family'] == 'RED' or ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Getting klnagent install package to temporary folder
      ansible.builtin.copy:
        src: "{{ klnagent_distrib_local_folder }}/{{ klnagent_rpm_package_name }}"
        dest: "{{ klnagent_distrib_remote_folder }}"
        mode: "0755"
    - name: Installing klnagent package
      ansible.builtin.yum:
        name: "{{ klnagent_distrib_remote_folder }}/{{ klnagent_rpm_package_name }}"
        disable_gpg_check: true


- name: Installing DEB to Debian Like
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Astra Linux'
  block:
    - name: Getting klnagent install package to temporary folder
      ansible.builtin.copy:
        src: "{{ klnagent_distrib_local_folder }}/{{ klnagent_deb_package_name }}"
        dest: "{{ klnagent_distrib_remote_folder }}"
        mode: "0755"
    - name: Installing klnagent package
      ansible.builtin.apt:
        deb: "{{ klnagent_distrib_remote_folder }}/{{ klnagent_deb_package_name }}"

- name: Creating answer file for klnagent
  become: true
  ansible.builtin.template:
    src: klnagent.j2
    dest: "{{ klnagent_answer_file_path }}"
    mode: "0644"

- name: Run configuring klnagent
  become: true
  ansible.builtin.command: /opt/kaspersky/klnagent64/lib/bin/setup/postinstall.pl
  environment:
    KLAUTOANSWERS: "{{ klnagent_answer_file_path }}"
  notify: restart klnagent
  changed_when: false

- name: Ensure klnagent service is enabled and restarted
  become: true
  ansible.builtin.service:
    name: klnagent64
    enabled: true
    state: restarted
