-  block:
    - name: "Remove previous agent installations"
      apt:
        name: klnagent64
        state: absent

    - name: "Deleting previous distros from tmp"
      file:
        path: "/tmp/klnagent"
        state: absent

    - name: "Deleting previous configs from agent"
      file:
        path: "/opt/kaspersky/klnagent64"
        state: absent
      file:
        path: "/var/opt/kasperksy/klnagent64"
        state: absent
